// <auto-generated />
using System;
using Assistente_de_Estagio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ADE.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200518180433_UserLogo")]
    partial class UserLogo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ADE.Dominio.Models.AlteracaoEntidadesSistema", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AutorId");

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao");

                    b.Property<DateTime>("DataHoraUltimaAlteracao");

                    b.Property<int>("Entidade");

                    b.Property<string>("IdAutor");

                    b.Property<int>("IdentificadorEntidade");

                    b.Property<string>("MensagemAlteracao");

                    b.HasKey("Identificador");

                    b.HasIndex("AutorId");

                    b.ToTable("AlteracaoEntidadesSistema");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Curso", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Alerta")
                        .HasColumnType("tinytext");

                    b.Property<int>("CargaHorariaMinimaEstagio")
                        .HasColumnType("int(11)");

                    b.Property<string>("CoordenadorCurso")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("DescricaoCurso")
                        .IsRequired()
                        .HasColumnType("tinytext");

                    b.Property<string>("EmailCoordenadorCurso")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("IdInstituicao")
                        .HasColumnType("int(11)");

                    b.Property<string>("Informacao")
                        .HasColumnType("tinytext");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(10);

                    b.Property<int>("TipoCurso");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdInstituicao");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Documento", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("Aviso")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("DescricaoDocumento")
                        .HasColumnType("tinytext");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<int>("IdCurso")
                        .HasColumnType("int(11)");

                    b.Property<sbyte>("PosicaoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValueSql("'1'");

                    b.Property<bool>("PossuiAssinaturaResposavelEstagio")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("PossuiCarimboCNPJ")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("PossuiData")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Texto")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("TituloDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdCurso")
                        .HasName("UKIdCurso");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("ADE.Dominio.Models.HistoricoGeracaoDocumento", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Documento")
                        .HasColumnName("IdDocumento")
                        .HasColumnType("int(11)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("Documento");

                    b.HasIndex("IdUsuario")
                        .HasName("IdUsuario");

                    b.ToTable("HistoricoGeracaoDocumento");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.AtividadeEstagio", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("CondicaoVezes");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descricao");

                    b.Property<string>("EnumEntidade")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<int>("IdCurso")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdentificadorEntidadeAtividade")
                        .HasColumnType("int(11)");

                    b.Property<int>("TipoAtividade");

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdCurso");

                    b.ToTable("AtividadeEstagio");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.AtividadeUsuario", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<bool>("Concluido");

                    b.Property<DateTime>("Data");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descricao");

                    b.Property<int>("IdCurso");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoAtividade")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuario");

                    b.ToTable("AtividadeUsuario");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.FAQ", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("IdInstituicao")
                        .HasColumnType("int(11)");

                    b.Property<string>("IdUsuarioPergunta")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdUsuarioResposta")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int(11)");

                    b.Property<string>("Resposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<string>("Status")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdInstituicao");

                    b.HasIndex("IdUsuarioResposta");

                    b.ToTable("FAQ");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.Instituicao", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Endereco")
                        .HasColumnType("varchar(256)");

                    b.Property<byte[]>("Logo")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Website")
                        .HasColumnType("varchar(256)");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.ToTable("Instituicao");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.LogAcoesEspeciais", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("AcoesSistema")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LocalOrigem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(150)")
                        .HasDefaultValueSql("'Error'");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LogAcoesEspeciais");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.Logins", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraLogin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraLogout")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraUltimaAlteracao");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuario")
                        .HasName("UKIdUsuario");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.MensagemIndividual", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("IdUsuarioDestino")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdUsuarioRemetente")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuarioRemetente");

                    b.ToTable("MensagemIndividual");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.NotificacaoIndividual", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Cabecalho")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("IdUsuarioDestino")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdUsuarioRemetente")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("NotificacaoIndividual");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.TourStep", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<string>("Controlador")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("IdElemento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<int>("Posicao")
                        .HasColumnType("int(11)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<string>("View")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.ToTable("TourStep");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.UsuarioADE", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("AceitouTermos");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao");

                    b.Property<DateTime>("DataHoraUltimaAlteracao");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("Estagiando");

                    b.Property<int>("IdCurso");

                    b.Property<int?>("IdCursoNavigationIdentificador");

                    b.Property<int>("IdInstituicao");

                    b.Property<int?>("IdInstituicaoNavigationIdentificador");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<bool>("Logado");

                    b.Property<byte[]>("Logo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<int>("Pontuacao");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("TipoRecebimentoNotificacao");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IdCursoNavigationIdentificador");

                    b.HasIndex("IdInstituicaoNavigationIdentificador");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ADE.Dominio.Models.InformacaoCurso", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConteudoInformacao")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int(11)");

                    b.Property<string>("TipoInformacao")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdCurso");

                    b.ToTable("InformacaoCurso");
                });

            modelBuilder.Entity("ADE.Dominio.Models.InformacaoDocumento", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConteudoInformacao")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int(11)");

                    b.Property<string>("TipoInformacao")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdDocumento");

                    b.ToTable("InformacaoDocumento");
                });

            modelBuilder.Entity("ADE.Dominio.Models.OpcaoRequisito", b =>
                {
                    b.Property<int>("IdRequisito")
                        .HasColumnType("int(11)");

                    b.Property<string>("Valor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("Identificador");

                    b.HasKey("IdRequisito", "Valor")
                        .HasName("PRIMARY");

                    b.HasAlternateKey("Identificador", "IdRequisito", "Valor");

                    b.ToTable("OpcaoRequisito");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RegistroDeHoras", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Atividade")
                        .IsRequired();

                    b.Property<float>("CargaHoraria");

                    b.Property<DateTime>("Data");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("HoraFim");

                    b.Property<DateTime>("HoraInicio");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RegistroDeHoras");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RelacaoEntidades.ConclusaoAtividadeCurso", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("IdAtividade")
                        .HasColumnType("int(11)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdAtividade");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ConclusaoAtividadeCurso");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RelacaoEntidades.ListaAmigos", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("IdAmigo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoRelacao")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdAmigo");

                    b.ToTable("ListaAmigos");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RelacaoEntidades.VisualizacaoNotificacaoGeral", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao");

                    b.Property<int>("IdNotificacao")
                        .HasColumnType("int(11)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.HasIndex("IdNotificacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("VisualizacaoNotificacaoGeral");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Requisito", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Bookmark")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ElementoHTMLRequisito")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("MascaraEntrada")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomeRequisito")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit(1)");

                    b.Property<string>("TipoElementoHTMLRequisito")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.ToTable("Requisito");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RequisitoDeDocumento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdRequisito")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("Identificador");

                    b.Property<sbyte>("OrdemRequisito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("IdDocumento", "IdRequisito")
                        .HasName("PRIMARY");

                    b.HasAlternateKey("IdDocumento", "Identificador", "IdRequisito");

                    b.HasIndex("IdDocumento")
                        .HasName("IdDocumento");

                    b.HasIndex("IdRequisito")
                        .HasName("IdRequisito");

                    b.ToTable("RequisitoDeDocumento");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RequisitoDeUsuario", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdRequisito")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("Identificador");

                    b.Property<string>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("varchar(256)");

                    b.HasKey("UserId", "IdRequisito")
                        .HasName("PRIMARY");

                    b.HasAlternateKey("Identificador", "IdRequisito", "UserId");

                    b.HasIndex("IdRequisito")
                        .HasName("FKRequisitoDeUsuarioIdRequisito");

                    b.ToTable("RequisitoDeUsuario");
                });

            modelBuilder.Entity("ADE.Dominio.Models.SysLogs", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("AcoesSistema")
                        .IsRequired()
                        .HasColumnName("Acao_IdAcao")
                        .IsUnicode(false);

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao");

                    b.Property<string>("LocalOrigem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(150)")
                        .HasDefaultValueSql("'Error'");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.ToTable("SysLogs");
                });

            modelBuilder.Entity("ADE.Dominio.Models.TermoCompromisso", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DataHoraExclusao");

                    b.Property<DateTime>("DataHoraInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DataHoraUltimaAlteracao");

                    b.Property<string>("Termos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'error'");

                    b.HasKey("Identificador")
                        .HasName("PRIMARY");

                    b.ToTable("TermoCompromisso");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ADE.Dominio.Models.AlteracaoEntidadesSistema", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "Autor")
                        .WithMany("AlteracaoEntidadesSistema")
                        .HasForeignKey("AutorId");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Curso", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.Instituicao", "Instituicao")
                        .WithMany("Cursos")
                        .HasForeignKey("IdInstituicao")
                        .HasConstraintName("UKIdInstituicao_Curso");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Documento", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Curso", "IdCursoNavigation")
                        .WithMany("Documento")
                        .HasForeignKey("IdCurso")
                        .HasConstraintName("UKIdCurso_Documento");
                });

            modelBuilder.Entity("ADE.Dominio.Models.HistoricoGeracaoDocumento", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("IdHistoricoGeracaoDocumento")
                        .HasForeignKey("Documento")
                        .HasConstraintName("HistoricoSistema_ibfk_2");

                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "IdUsuarioNavigation")
                        .WithMany("HistoricoGeracaoDocumento")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("HistoricoSistema_ibfk_1");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.AtividadeEstagio", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Curso", "Curso")
                        .WithMany("Atividades")
                        .HasForeignKey("IdCurso")
                        .HasConstraintName("FKAtividadeEstagioIdCurso");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.AtividadeUsuario", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "Usuario")
                        .WithMany("AtividadesUsuario")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FKAtividadeUsuarioIdUsuario");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.FAQ", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.Instituicao", "Instituicao")
                        .WithMany("FAQ")
                        .HasForeignKey("IdInstituicao")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "IdUsuarioNavigation")
                        .WithMany("FAQS")
                        .HasForeignKey("IdUsuarioResposta");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.LogAcoesEspeciais", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "IdUsuarioNavigation")
                        .WithMany("LogAcoesEspeciais")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("HistoricoEspecialSistema_ibfk_1");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.Logins", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "Usuario")
                        .WithMany("Logins")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("UKIdUsuario_Logins");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.MensagemIndividual", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "IdUsuarioNavigation")
                        .WithMany("Mensagems")
                        .HasForeignKey("IdUsuarioRemetente");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.NotificacaoIndividual", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "IdUsuarioNavigation")
                        .WithMany("NotificacoesIndividuais")
                        .HasForeignKey("IdUsuarioDestino");
                });

            modelBuilder.Entity("ADE.Dominio.Models.Individuais.UsuarioADE", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Curso", "IdCursoNavigation")
                        .WithMany()
                        .HasForeignKey("IdCursoNavigationIdentificador");

                    b.HasOne("ADE.Dominio.Models.Individuais.Instituicao", "IdInstituicaoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdInstituicaoNavigationIdentificador");
                });

            modelBuilder.Entity("ADE.Dominio.Models.InformacaoCurso", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Curso", "IdCursoNavigation")
                        .WithMany("InformacaoCursos")
                        .HasForeignKey("IdCurso");
                });

            modelBuilder.Entity("ADE.Dominio.Models.InformacaoDocumento", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("InformacaoDocumentos")
                        .HasForeignKey("IdDocumento");
                });

            modelBuilder.Entity("ADE.Dominio.Models.OpcaoRequisito", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Requisito", "IdRequisitoNavigation")
                        .WithMany("OpcaoRequisito")
                        .HasForeignKey("IdRequisito");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RegistroDeHoras", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "Usuario")
                        .WithMany("RegistroDeHoras")
                        .HasForeignKey("IdUsuario");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RelacaoEntidades.ConclusaoAtividadeCurso", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.AtividadeEstagio", "Atividade")
                        .WithMany("ConclusoesAtividade")
                        .HasForeignKey("IdAtividade")
                        .HasConstraintName("FKConclusaoAtividadeCursoIdAtividade");

                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "Usuario")
                        .WithMany("ConclusaoAtividadeCurso")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FKConclusaoAtividadeCursoIdUsuario");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RelacaoEntidades.ListaAmigos", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "IdUsuarioNavigation")
                        .WithMany("ListaAmigos")
                        .HasForeignKey("IdAmigo");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RelacaoEntidades.VisualizacaoNotificacaoGeral", b =>
                {
                    b.HasOne("ADE.Dominio.Models.AlteracaoEntidadesSistema", "IdNotificacaoNavigation")
                        .WithMany("Notificacao")
                        .HasForeignKey("IdNotificacao")
                        .HasConstraintName("UKIdNotificacao_VisualizacaoNotificacao");

                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "IdUsuarioNavigation")
                        .WithMany("NotificacoesVisualizadas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("VisualizacaoNotificacao_ibfk_1");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RequisitoDeDocumento", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("RequisitoDeDocumento")
                        .HasForeignKey("IdDocumento")
                        .HasConstraintName("IdDocumento");

                    b.HasOne("ADE.Dominio.Models.Requisito", "IdRequisitoNavigation")
                        .WithMany("RequisitoDeDocumento")
                        .HasForeignKey("IdRequisito")
                        .HasConstraintName("IdRequisito");
                });

            modelBuilder.Entity("ADE.Dominio.Models.RequisitoDeUsuario", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Requisito", "IdRequisitoNavigation")
                        .WithMany("RequisitoDeUsuario")
                        .HasForeignKey("IdRequisito")
                        .HasConstraintName("FKRequisitoDeUsuarioIdRequisito");

                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE", "User")
                        .WithMany("RequisitoDeUsuario")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ADE.Dominio.Models.Individuais.UsuarioADE")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
