namespace ADE.Dominio.Models.Enums
{
    public enum EnumTipoLog
    {
        CriacaoArquivo = 1,
        ImpressaoArquivo = 2,
        RegistroDeUsuario = 3,
        Login = 4,
        DelecaoConta = 5,
        AlteracaoSenha = 6,
        CriacaoDocumento = 7,
        AlteracaoDocumento = 8,
        DelecaoDocumento = 9,
        CriacaoCurso = 10,
        AlteracaoCurso = 11,
        DelecaoCurso = 12,
        CriacaoRequisito = 13,
        AlteracaoRequisito = 14,
        DelecaoRequisito = 15,
        CriacaoRequisitoDeDocumento = 16,
        AlteracaoRequisitoDeDocumento = 17,
        DelecaoRequisitoDeDocumento = 18,
        CriacaoRequisitoDeUsuario = 19,
        AlteracaoRequisitoDeUsuario = 20,
        DelecaoRequisitoDeUsuario = 21,
        ErroConexao = 22,
        ErroInterno = 23,
        DownloadDadosPessoais = 24,
        Outro = 25,
        RegistroDeAdministrador = 26,
        AlteracaoUsuario = 27,
        DelecaoUsuario = 28,
        CriacaoInstituicao = 29,
        AlteracaoInstituicao = 30,
        DelecaoInstituicao = 31,
        AlteracaoCursoUsuario = 32,
        AlteracaoInstituicaoUsuario = 33,
        CriacaoFAQ = 34,
        AlteracaoFAQ = 35,
        DelecaoFAQ = 36,
        AlteracaoNomeUsuario = 37,
        AlteracaoEmailUsuario = 38,
        CriacaoRegistroHoras = 39,
        AlteracaoRegistroHoras = 40,
        DelecaoRegistroHoras = 41,
        CriacaoTermoCompromisso = 42,
        AlteracaoTermoCompromisso = 43,
        DelecaoTermoCompromisso = 44,
        CriacaoAtividadeUsuario = 45,
        AlteracaoAtividadeUsuario = 46,
        DelecaoAtividadeUsuario = 47,
        VisualizacaoHistoricoAtividades = 48,
        ListaPerfis = 49,
        PerfilUsuario = 50
    }
}
